use libc::c_int;

pub type ImGuiDebugLogFlags = c_int;

pub const IM_GUI_DEBUG_LOG_FLAGS_NONE: ImGuiDebugLogFlags = 0;
pub const IM_GUI_DEBUG_LOG_FLAGS_EVENT_ACTIVE_ID: ImGuiDebugLogFlags = 1 << 0;
pub const IM_GUI_DEBUG_LOG_FLAGS_EVENT_FOCUS: ImGuiDebugLogFlags = 1 << 1;
pub const IM_GUI_DEBUG_LOG_FLAGS_EVENT_POPUP: ImGuiDebugLogFlags = 1 << 2;
pub const IM_GUI_DEBUG_LOG_FLAGS_EVENT_NAV: ImGuiDebugLogFlags = 1 << 3;
pub const IM_GUI_DEBUG_LOG_FLAGS_EVENT_CLIPPER: ImGuiDebugLogFlags = 1 << 4;
pub const IM_GUI_DEBUG_LOG_FLAGS_EVENT_IO: ImGuiDebugLogFlags = 1 << 5;
pub const IM_GUI_DEBUG_LOG_FLAGS_EVENT_DOCKING: ImGuiDebugLogFlags = 1 << 6;
pub const IM_GUI_DEBUG_LOG_FLAGS_EVENT_VIEWPORT: ImGuiDebugLogFlags = 1 << 7;
pub const IM_GUI_DEBUG_LOG_FLAGS_EVENT_MASK: ImGuiDebugLogFlags =
    IM_GUI_DEBUG_LOG_FLAGS_EVENT_ACTIVE_ID
        | IM_GUI_DEBUG_LOG_FLAGS_EVENT_FOCUS
        | IM_GUI_DEBUG_LOG_FLAGS_EVENT_POPUP
        | IM_GUI_DEBUG_LOG_FLAGS_EVENT_NAV
        | IM_GUI_DEBUG_LOG_FLAGS_EVENT_CLIPPER
        | IM_GUI_DEBUG_LOG_FLAGS_EVENT_IO
        | IM_GUI_DEBUG_LOG_FLAGS_EVENT_DOCKING
        | IM_GUI_DEBUG_LOG_FLAGS_EVENT_VIEWPORT;
pub const IM_GUI_DEBUG_LOG_FLAGS_OUTPUT_TO_TTY: ImGuiDebugLogFlags = 1 << 10;
